config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'

  resources :books, only: [:index, :show, :create, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]
  #resources :applications, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base


  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  validates :name, length: {in: 2..20}, uniqueness: true
  validates :introduction, length: { maximum: 50 }


  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100,100]).processed
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end




  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def update
    @book = Book.find(params[:id]) 
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
  end

  def edit
    @book = Book.find(params[:id])

    book = Book.find(params[:id])
    unless book.user_id == current_user.id
      redirect_to books_path
    end
  end



  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "You have deleted book successfully."
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_sidebar.html.erb
<h2>user info</h2>
        <% if user.profile_image.attached? %>
          <%= image_tag user.profile_image, size: "100x100" %>
        <% else %>
          <%= image_tag 'no_image' %>
        <% end %>

      <table class="table">
        <tbody>
          <tr>
            <th scope="row">name</th>
            <td><%= user.name %></td>
          </tr>
          <tr>
            <th scope="row">introduction</th>
            <td><%= user.introduction %></td>
          </tr>
        </tbody>
      </table>

      <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fa-solid fa-user-gear"></i>
      <% end %>

      <h2>New book</h2>
        <%= form_with model: book do |f| %>
          <p>Title</p>
            <%= f.text_field :title %>
          <p>Opinion</p>
            <%= f.text_area :body %><br>
          <%= f.submit 'Create Book', class: "btn btn-success" %>
        <% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>

  <p>Title</p>
  <%= f.text_field :title %>

  <p>Opinion</p>
  <%= f.text_area :body %>
<br>
  <%= f.submit 'Update Book' %>
<p>
  <%= link_to "Show", book_path(@book.id) %>
  <%= link_to "Back", "/books" %>
</p>
<% end %>

app/views/books/index.html.erb
<% if @book.errors.any? %>
<%= @book.errors.count %> errors prohibited this obj from being saved:
<ul>
  <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'sidebar', user: current_user, book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do%>
                <%= image_tag book.user.get_profile_image %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'sidebar', user: @book.user, book: @book_new %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>
      <table class="table">
        <tbody>
            <tr>
            <th scope="row">
              <%= image_tag @book.user.profile_image, size:"100x100" %> <br>
              <%= link_to user_path(@book.user.id) do %>
              <%= @book.user.name %>   
              <% end %>
            </th>
            <td><%= @book.title %></td>
            <td><%= @book.body %></td>
              <% if @book.user == current_user %>
            <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success" %></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-danger" %></td>
              <% end %>
            </tr>
         </tbody>
       </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="px-3 mx-auto">
      <h1>Welcome to <i class="fa-solid fa-book"></i>Bookers!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container mt-5">
<div class="row">
  <div class="mx-auto">

<h1>welcome to <i class="fa-solid fa-book"></i>Bookers!!</h1>
<p>In <i class="fa-solid fa-book"></i>Bookers,</p>
<p>you can share and exchange your opinions, impressions, and emotions</p>
<p>about various books!</p>

<%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-block" %></button>
<br>
<br>
<%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-block" %></button>


</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/5a2608659f.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
       <a class="navbar-brand" href="/">Bookers</a>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li class="nav-item">
              <%= link_to user_path(current_user.id), class:"nav-link text-light" do %>
                <i class="fa-solid fa-house"></i>Home
              <% end %>
          </li>
          <li class="nav-item">
            <a class ="nav-link text-light" href="/users">
            <i class="fa-solid fa-users"></i>Users
            </a>
          </li>
          <li class="nav-item">
            <a class ="nav-link text-light" href="/books">
            <i class="fa-solid fa-book-open"></i>Books
            </a>
          </li>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, class:"nav-link text-light", method: :delete do %>
              <i class="fa-solid fa-right-from-bracket"></i>Log out
            <% end %>
          </li>
          <% else %>
          <li class="nav-item">
            <a class="nav-link text-light", href="/">
              <i class="fa-solid fa-house"></i>Home
            </a>
          </li>
          <li class="nav-item">
            <%= link_to about_path, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-link"></i>About
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-user-plus"></i>Sign up
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-right-to-bracket"></i>Log in
            <% end %>
          </li>
          <% end %>
          </ul>
        </div>
      </div>
    </nav>
    </header>
    <main>


    <% flash.each do |message_type, message| %>
      <div class="flash-message <%= message_type %>"><%= message %></div>
    <% end %>

      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
<h2>User info</h2>

<% if @user.errors.any? %>
<%= @user.errors.count %> errors prohibited this obj from being saved:
<ul>
  <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>

<%= form_with model: @user do |f| %>
  <p>Name</p>
    <%= f.text_field :name %>
  <p>Image</p>
    <%= f.file_field :profile_image, accept: "image/*" %>
  <p>Introduction</p>
    <%= f.text_area :introduction %><br>
  <%= f.submit 'Update User', class: "btn btn-secondary" %>
  </button>
<% end %>
</div>
</div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/sidebar', user: current_user, book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h1>Users</h1>
      <table class ="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <% if user.profile_image.attached? %>
                  <%= image_tag user.get_profile_image %>
                <% else %>
                  <%= image_tag 'no_image' %>
                <% end %>
              </td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/sidebar', user: @user, book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
<h1>Books</h1>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
        <%= link_to user_path(book.user.id) do%>
          <% if @user.profile_image.attached? %>
            <%= image_tag @user.get_profile_image %>
          <% else %>
            <%= image_tag 'no_image' %>
          <% end %>
        <% end %>
        </td>
        <td><%= link_to book_path(book.id) do %>
          <%= book.title %>
        <% end %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>